// Writes docs/colour-themes.md from the sources, so another project can take these
// colours without copying them out of a running app.
//
//   node web/tools/export-theme.mjs
//
// **Generated, not written.** The palettes live in one place and the semantic tokens in
// another, and a hand-kept document describing both is a document that is wrong within a
// month — quietly, because nobody re-reads a colour table. This reads both files and
// emits what they currently say.
//
// The derived stops are the part that cannot be hand-written at all. The eight bands of
// a palette are a ramp chosen for character, not for contrast, and the app never renders
// them as stored: `paletteFor` samples the ramp to the number of highlights on the page
// and moves each stop into the register's legible window. Publishing the raw bands alone
// would hand another project colours this app does not use. So they are computed here by
// calling the real function.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PALETTES, PALETTE_NAMES, paletteFor } from '../src/lib/reading.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT = join(REPO, 'docs', 'colour-themes.md');

/** Pull `--name: value;` declarations out of one CSS block, keeping source order. */
function tokensIn(css, selector) {
  // The block is everything between the selector's brace and its matching close. These
  // files have no nested blocks inside :root or .shore, so the first } is the right one.
  const start = css.indexOf(selector);
  if (start < 0) return [];
  const open = css.indexOf('{', start);
  const close = css.indexOf('}', open);
  const body = css.slice(open + 1, close);

  const out = [];
  for (const line of body.split('\n')) {
    const match = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+);/);
    if (!match) continue;
    const comment = line.match(/\/\*\s*(.+?)\s*\*\//);
    out.push({ name: match[1], value: match[2].trim(), note: comment ? comment[1] : null });
  }
  return out;
}

/** A markdown table of tokens, with the group headings the CSS comments already carry. */
function tokenTable(tokens) {
  const rows = tokens.map(
    ({ name, value, note }) => `| \`${name}\` | \`${value}\` | ${note || ''} |`,
  );
  return ['| Token | Value | |', '| --- | --- | --- |', ...rows].join('\n');
}

function swatchRow(colours) {
  return colours.map((c) => `\`${c.toUpperCase()}\``).join(' ');
}

const colorsCss = readFileSync(join(REPO, 'web/src/ds/tokens/colors.css'), 'utf8');
const readingJs = readFileSync(join(REPO, 'web/src/lib/reading.js'), 'utf8');

/** A `const NAME = value;` out of reading.js, so the constants table cannot drift from
 *  the code it describes — which is the whole claim this file makes at the top. */
function constantIn(name) {
  // Doubled backslashes: this is a template literal, so `\s` would collapse to a bare
  // `s` before RegExp ever saw it, and the pattern would hunt for "consts+NAME".
  const match = readingJs.match(new RegExp(`const\\s+${name}\\s*=\\s*([^;]+);`));
  if (!match) throw new Error(`${name} is no longer in reading.js — fix this exporter.`);
  return match[1].trim();
}

// Name, and what it does. The value comes from the source; only the explanation is here,
// because the source cannot say why in a table cell.
const CONSTANTS = [
  ['NIGHT_MIN_LUM', 'Contrast backstop on deep ground. Deliberately not maximal — it measures ~5.5:1, and every point above is paid for in collapsed stops.'],
  ['DAY_MAX_LUM', 'The same backstop on paper.'],
  ['NIGHT_LIGHTNESS', 'The window the ramp is rescaled into at night.'],
  ['DAY_LIGHTNESS', 'The same window on paper.'],
  ['SATURATION_BOOST', 'Chroma multiplier applied while hue is held.'],
  ['SATURATION_FLOOR', 'Below this a stop reads as grey whatever its hue.'],
  ['NEUTRAL', 'Under this saturation there is no hue worth amplifying — bee opens at `#1A141A`.'],
];
const night = tokensIn(colorsCss, ':root');
const day = tokensIn(colorsCss, '.shore');

const lines = [];
const push = (...text) => lines.push(...text);

push(
  '# Colour themes',
  '',
  '**Generated by `node web/tools/export-theme.mjs` — do not edit by hand.**',
  'It reads `web/src/ds/tokens/colors.css` and `web/src/lib/reading.js`, so anything here',
  'is what the app currently uses rather than what somebody once wrote down.',
  '',
  'Two systems live here and they answer different questions.',
  '',
  '- **The register tokens** are the room: surfaces, text, borders, the accent. Two',
  '  registers, day and night, and an app picks one at a time.',
  '- **The reading palettes** are the marks: eight bands handed out in reading order to',
  '  the highlighted phrases on a page. Five of them, and the reader chooses.',
  '',
  '---',
  '',
  '## 1. Register tokens',
  '',
  'Night is the default and lives on `:root`; day is a `.shore` class on an ancestor, so',
  'switching register is one class and never a repaint of every rule. The raw ramps come',
  'first and the semantic names point at them — **use the semantic names.** `--accent`',
  'survives a change of palette; `--shore-500` is a fact about one ramp.',
  '',
  '### Night (`:root`)',
  '',
  tokenTable(night),
  '',
  '### Day (`.shore`)',
  '',
  'Only what changes is redefined; everything else inherits from `:root` above.',
  '',
  tokenTable(day),
  '',
  '---',
  '',
  '## 2. Reading palettes',
  '',
  'Eight bands each, in the order they are handed out: the first highlighted phrase on a',
  'page takes band 1, the second band 2, and so on.',
  '',
  '**These are not the colours that get drawn.** They are a ramp chosen for character,',
  'not for contrast against a page, and rendering them as stored is the mistake this',
  'section exists to prevent. What the reader actually paints is in §3.',
  '',
);

for (const name of PALETTE_NAMES) {
  push(`### ${name}`, '', swatchRow(PALETTES[name]), '');
}

push(
  '---',
  '',
  '## 3. What actually gets drawn',
  '',
  'A page rarely has eight highlights, and the bands are too dark or too light to read',
  'against either ground as they stand. `paletteFor(name, day, count)` does two things:',
  '',
  '1. **Samples the ramp to `count`.** Four highlights take four stops spread across the',
  '   whole spectrum, not the first four bands — otherwise a short page only ever sees the',
  '   dark end and the palette never arrives.',
  '2. **Moves each stop into the register\'s legible window**, preserving hue.',
  '',
  'Below is `count = 8` in both registers: the eight stops a full page is painted in.',
  '',
);

for (const name of PALETTE_NAMES) {
  push(
    `### ${name}`,
    '',
    `- **night** — ${swatchRow(paletteFor(name, false, 8))}`,
    `- **day** — ${swatchRow(paletteFor(name, true, 8))}`,
    '',
  );
}

push(
  '---',
  '',
  '## 4. Porting the legibility pass',
  '',
  'If you only need the colours, take §3 and stop reading. If you need to derive stops for',
  'a count this file does not list, port `legible()` and `paletteFor()` from',
  '`web/src/lib/reading.js` — and know the two traps, both of which were shipped here',
  'before being measured and reverted.',
  '',
  '**Do not mix toward ink or cream to reach contrast.** It clears the contrast floor by',
  'pulling every band toward grey. At night it produced literal greys — sunset opened',
  '`#C0BCC7 #C0B4BC #BFA7C6` — at mean saturation 0.41. Hold the hue and raise chroma',
  'instead; the same palette now runs 0.71.',
  '',
  '**Do not pin every stop to the contrast floor.** Bands that differ mainly in lightness',
  'then collapse onto each other: sunrise is four teals followed by four oranges, and a',
  'hard floor put adjacent stops at ΔE 2, which is no visible difference. Rescale the',
  "palette's own lightness spread into the register's window and keep the floor as a",
  'backstop only.',
  '',
  'The constants, from the same file:',
  '',
  '| Constant | Value | What it does |',
  '| --- | --- | --- |',
  ...CONSTANTS.map(([name, what]) => `| \`${name}\` | \`${constantIn(name)}\` | ${what} |`),
  '',
  '`node web/tools/check-palettes.mjs` prints contrast, saturation and adjacent ΔE for',
  'every palette in both registers, against the previous behaviour. Re-run it if any of',
  'these numbers are touched.',
  '',
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`wrote ${OUT}`);
console.log(`  ${night.length} night tokens, ${day.length} day tokens, ${PALETTE_NAMES.length} palettes`);
